# -*- coding: utf-8 -*-
"""Tugas5-List dan Condition Match.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DlyBdfrpXnleTDY8eQwNt3n7M1-4TY6q
"""

kendaraan = ["Mio","Motor", "150", "Kuning", "2"]
kendaraan.append("3000000")
kendaraan.append("Matic")

kendaraan.insert(2,"Yamaha")

print(kendaraan)

Pesan="""
Menu :
1.menghitung luas persegi
2.menghitung luas lingkaran
3.menghitung luas segitiga
pilihan menu:
"""

Pilihan = input(Pesan)

match Pilihan:
    case"1":
      print("anda memasukan angka 1 untuk menghitung luas persegi")
      sisi = float(input("masukan sisi:"))
      luasp = sisi*sisi
      print("luas persegi dengan sisi ",sisi, "adalah", luasp)
    case"2":
      print("kamu memasukan angka 2 untuk menghitung luas lingkaran")
      jari = float(input("masukan jari-jari: "))
      luasl =3,14*jari*jari
      print("luas lingkaran yang jari-jarinya ",jari,"adalah",luasl)
    case"3":
      print("kamu memasukan angka 3 untuk menghitung luas segitiga")
      alas = int(input("masukan alas: "))
      tinggi = int(input("masukan tinggi: "))
      luass = 0,5*alas*tinggi
      print("luas segitiga yang alasnya",alas, " dan tingginya ",tinggi," adalah", luass)
    case _:
      print("anda salah memilih")